### ISSUE TITLE
Configuration examples

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#20]
* [x] Portainer integration (https://github.com/amazeeio/pygmy/pull/18)
* [x] HTTPS example
* [x] Custom image example
* [ ] Custom domain/resolver example

If anybody would like more examples which will showcase what's possible here please comment here. It's borderline-docker-compose without compose - so we just need to selectively target a bunch of solid examples.

### Example: Portainer
**Services**
```yaml
  amazeeio-portainer:
    Name: amazeeio-portainer
    Disabled: false
    Config:
      Image: portainer/portainer
    HostConfig:
      Binds:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      PortBindings:
        8000/tcp:
          -
            HostPort: 8000
        9000/tcp:
          -
            HostPort: 9000
```

**Volumes**:
```...yml
volumes:
  - portainer_data
```
```
