### ISSUE TITLE
Request for example pygmy portainer integration

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#62]
**Background**

Portainer is a useful application for people new to Docker and folks interested in poking around. It has previously been submitted for a PR in the original Pygmy project (https://github.com/amazeeio/pygmy/pull/18)

**Implementation**

__Docker__

```
docker volume create portainer_data
docker run -d -p 8000:8000 -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
```

__Variables__

```
n/a
```

__Volumes__

```
- portainer_data
```

**Comment by fubarhouse** [comment]
**Services**
```
  amazeeio-portainer:
    Name: amazeeio-portainer
    Config:
      Image: portainer/portainer
    HostConfig:
      Binds:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      PortBindings:
        8000/tcp:
          -
            HostPort: 8000
        9000/tcp:
          -
            HostPort: 9000
```

**Volumes**
```
volumes:
  - portainer_data
```

**Comment by fubarhouse** [comment]
Improvements and compatibility with master after #123 is merged - this will be compatible with `v0.2`.

```yaml
services:
  amazeeio-portainer:
    Config:
      Image: portainer/portainer
      Env:
        - "AMAZEEIO=AMAZEEIO"
        - "AMAZEEIO_URL=portainer.docker.amazee.io"
        - "AMAZEEIO_HTTP_PORT=9000"
      Labels:
        - pygmy: pygmy
        - pygmy.enable: true
        - pygmy.name: amazeeio-portainer
        - pygmy.weight: 23
        - pygmy.url: http://portainer.docker.amazee.io
      ExposedPorts:
        9000/tcp: {}
    HostConfig:
      Binds:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      PortBindings:
        8000/tcp:
          - HostPort: 8200
        9000/tcp:
          - HostPort: 8100

volumes:
  portainer_data:
    Name: portainer_data
```
