### ISSUE TITLE
Request for example pygmy cowsay integration

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#63]
**Background**

This configuration example serves no practical application, however provides a POC example for showing the stdout of a container on-start to achieve a specific outcome. In this case we would be running an arbitrary image, passing arguments onto the container in typical `docker run ...` fashion.

**Implementation**

__Docker__

```
docker run -it --rm mbentley/cowsay holy ship!
```

__Variables__

n/a

__Volumes__

n/a

**Comment by fubarhouse** [comment]
**Services**
```
  example-cowsay:
    name: example-cowsay
    discrete: true
    output: true
    weight: 99
    Config:
      Image: mbentley/cowsay
      Cmd:
        - holy
        - ship
    HostConfig:
      AutoRemove: true
```

**Comment by fubarhouse** [comment]
Note that output logic needs work, but the following config works.

```yaml
  example-cowsay:
    name: example-cowsay
    Config:
      Image: mbentley/cowsay
      Cmd:
        - holy
        - ship
      Labels:
        - pygmy: pygmy
        - pygmy.enable: true
        - pygmy.discrete: true
        - pygmy.name: example-cowsay
        - pygmy.output: true
        - pygmy.weight: 99
    HostConfig:
      AutoRemove: true
```
