### ISSUE TITLE
Request for example pygmy https integration

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#66]
**Background**

A popular request is to run pygmy on https (443) which is currently supported out of the box however requires minimal effort to get it going. Port 443 is disabled by default with this software application, so simply switching from port 80 to 443 would be suitable.

**Implementation**

__Docker__

```
docker run -d -p 443:443 --volume=/var/run/docker.sock:/tmp/docker.sock --restart=always --name=amazeeio-haproxy amazeeio/haproxy
```

__Variables__

n/a

__Volumes__

n/a

**Comment by fubarhouse** [comment]
**Services**
```
  amazeeio-haproxy:
    Config:
      PortBindings:
        443/tcp:
        - HostPort: 443
```
