### ISSUE TITLE
Request for example pygmy custom image integration

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#67]
**Background**

For users wanting to bring their own images to pygmy to override existing images.

**Implementation**

__Docker__

```
docker run -d -p 8080:8080 --volume=/var/run/docker.sock:/tmp/docker.sock --restart=always --name=amazeeio-haproxy fubarhouse/amazeeio-haproxy-8080
```

__Variables__

n/a

__Volumes__

n/a

**Comment by fubarhouse** [comment]
**Description**
The following image was produced because ports `80` and `443` were unavailable for use in automated testing. So the HAProxy image was forked and rebuilt to expose port `8080` and to change the template configuration so that all proxy forwarding would still operate, and as a result we can perform `curl http://docker.amazee.io:8080/stats` for very real application testing.

https://github.com/fubarhouse/pygmy-go/blob/master/.travis.yml#L22

**Services**
```
  amazeeio-haproxy:
    Config:
      Image: fubarhouse/amazeeio-haproxy-8080
    HostConfig:
      PortBindings:
        8080/tcp:
          -
            HostPort: 8080
```
