### ISSUE TITLE
Request for example pygmy non-standard mailhog port

### ISSUE THREAD

**Issue by fubarhouse** [pygmystack/pygmy#85]
**Background**

To avoid port conflict for other mailhog instances, it could be useful to run Pygmy's mailhog on separate ports.

**Implementation**

__Docker__

```
docker run --restart unless-stopped --name mailhog -p 2025:1025 -d mailhog/mailhog
```

__Variables__

```
n/a
```

__Volumes__

```
n/a
```

**Comment by fubarhouse** [comment]
Noting that MailHub ports will need to be changed on the container (SMTP configuration) to match the new port, the following will change the port binding on the host to `2025` to allow for multiple mailhog instances to be ran locally - though other mailhog instances would need such configuration and consideration. This has been tested:
```
services:
  amazeeio-mailhog:
    HostConfig:
      PortBindings:
        1025/tcp:
        - HostPort: 2025
```

More information: https://pastebin.com/UPFdfJFQ
